Dev deployment test (#513)
* Fixes logo issue #428 in CB hangout reminder email (#434)

* Fixes logo issue #428 in CB hangout reminder email

* Changed img src to {{logo}} fixing logo issue #428

* Changed logo image from logo.svg to logo-circle.png

* display url links in learning items (#493)

* Runtime error fix. (#408)

Helper functions are now being added on creation of the template instead on render.

This was cauing `Exception in template helper: TypeError: Template.instance(...).loadHangouts is not a function` to occur.

* update meteor version

* add deployment scripts

* fix CI stuff

* update release.txt

* minor tweaks

* resolve bcrypt err in prod

* test commit in dev-development branch